// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lenon/gofii/ent/fnetdocument"
	"github.com/lenon/gofii/ent/fnetsubcategory2"
	"github.com/lenon/gofii/ent/predicate"
)

// FnetSubCategory2Query is the builder for querying FnetSubCategory2 entities.
type FnetSubCategory2Query struct {
	config
	limit         *int
	offset        *int
	unique        *bool
	order         []OrderFunc
	fields        []string
	predicates    []predicate.FnetSubCategory2
	withDocuments *FnetDocumentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FnetSubCategory2Query builder.
func (fsc *FnetSubCategory2Query) Where(ps ...predicate.FnetSubCategory2) *FnetSubCategory2Query {
	fsc.predicates = append(fsc.predicates, ps...)
	return fsc
}

// Limit adds a limit step to the query.
func (fsc *FnetSubCategory2Query) Limit(limit int) *FnetSubCategory2Query {
	fsc.limit = &limit
	return fsc
}

// Offset adds an offset step to the query.
func (fsc *FnetSubCategory2Query) Offset(offset int) *FnetSubCategory2Query {
	fsc.offset = &offset
	return fsc
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fsc *FnetSubCategory2Query) Unique(unique bool) *FnetSubCategory2Query {
	fsc.unique = &unique
	return fsc
}

// Order adds an order step to the query.
func (fsc *FnetSubCategory2Query) Order(o ...OrderFunc) *FnetSubCategory2Query {
	fsc.order = append(fsc.order, o...)
	return fsc
}

// QueryDocuments chains the current query on the "documents" edge.
func (fsc *FnetSubCategory2Query) QueryDocuments() *FnetDocumentQuery {
	query := &FnetDocumentQuery{config: fsc.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fsc.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fsc.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fnetsubcategory2.Table, fnetsubcategory2.FieldID, selector),
			sqlgraph.To(fnetdocument.Table, fnetdocument.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, fnetsubcategory2.DocumentsTable, fnetsubcategory2.DocumentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(fsc.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FnetSubCategory2 entity from the query.
// Returns a *NotFoundError when no FnetSubCategory2 was found.
func (fsc *FnetSubCategory2Query) First(ctx context.Context) (*FnetSubCategory2, error) {
	nodes, err := fsc.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fnetsubcategory2.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fsc *FnetSubCategory2Query) FirstX(ctx context.Context) *FnetSubCategory2 {
	node, err := fsc.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FnetSubCategory2 ID from the query.
// Returns a *NotFoundError when no FnetSubCategory2 ID was found.
func (fsc *FnetSubCategory2Query) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsc.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fnetsubcategory2.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fsc *FnetSubCategory2Query) FirstIDX(ctx context.Context) int {
	id, err := fsc.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FnetSubCategory2 entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FnetSubCategory2 entity is found.
// Returns a *NotFoundError when no FnetSubCategory2 entities are found.
func (fsc *FnetSubCategory2Query) Only(ctx context.Context) (*FnetSubCategory2, error) {
	nodes, err := fsc.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fnetsubcategory2.Label}
	default:
		return nil, &NotSingularError{fnetsubcategory2.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fsc *FnetSubCategory2Query) OnlyX(ctx context.Context) *FnetSubCategory2 {
	node, err := fsc.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FnetSubCategory2 ID in the query.
// Returns a *NotSingularError when more than one FnetSubCategory2 ID is found.
// Returns a *NotFoundError when no entities are found.
func (fsc *FnetSubCategory2Query) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fsc.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fnetsubcategory2.Label}
	default:
		err = &NotSingularError{fnetsubcategory2.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fsc *FnetSubCategory2Query) OnlyIDX(ctx context.Context) int {
	id, err := fsc.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FnetSubCategory2s.
func (fsc *FnetSubCategory2Query) All(ctx context.Context) ([]*FnetSubCategory2, error) {
	if err := fsc.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return fsc.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (fsc *FnetSubCategory2Query) AllX(ctx context.Context) []*FnetSubCategory2 {
	nodes, err := fsc.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FnetSubCategory2 IDs.
func (fsc *FnetSubCategory2Query) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := fsc.Select(fnetsubcategory2.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fsc *FnetSubCategory2Query) IDsX(ctx context.Context) []int {
	ids, err := fsc.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fsc *FnetSubCategory2Query) Count(ctx context.Context) (int, error) {
	if err := fsc.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return fsc.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (fsc *FnetSubCategory2Query) CountX(ctx context.Context) int {
	count, err := fsc.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fsc *FnetSubCategory2Query) Exist(ctx context.Context) (bool, error) {
	if err := fsc.prepareQuery(ctx); err != nil {
		return false, err
	}
	return fsc.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (fsc *FnetSubCategory2Query) ExistX(ctx context.Context) bool {
	exist, err := fsc.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FnetSubCategory2Query builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fsc *FnetSubCategory2Query) Clone() *FnetSubCategory2Query {
	if fsc == nil {
		return nil
	}
	return &FnetSubCategory2Query{
		config:        fsc.config,
		limit:         fsc.limit,
		offset:        fsc.offset,
		order:         append([]OrderFunc{}, fsc.order...),
		predicates:    append([]predicate.FnetSubCategory2{}, fsc.predicates...),
		withDocuments: fsc.withDocuments.Clone(),
		// clone intermediate query.
		sql:    fsc.sql.Clone(),
		path:   fsc.path,
		unique: fsc.unique,
	}
}

// WithDocuments tells the query-builder to eager-load the nodes that are connected to
// the "documents" edge. The optional arguments are used to configure the query builder of the edge.
func (fsc *FnetSubCategory2Query) WithDocuments(opts ...func(*FnetDocumentQuery)) *FnetSubCategory2Query {
	query := &FnetDocumentQuery{config: fsc.config}
	for _, opt := range opts {
		opt(query)
	}
	fsc.withDocuments = query
	return fsc
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FnetSubCategory2.Query().
//		GroupBy(fnetsubcategory2.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fsc *FnetSubCategory2Query) GroupBy(field string, fields ...string) *FnetSubCategory2GroupBy {
	grbuild := &FnetSubCategory2GroupBy{config: fsc.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := fsc.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return fsc.sqlQuery(ctx), nil
	}
	grbuild.label = fnetsubcategory2.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.FnetSubCategory2.Query().
//		Select(fnetsubcategory2.FieldName).
//		Scan(ctx, &v)
func (fsc *FnetSubCategory2Query) Select(fields ...string) *FnetSubCategory2Select {
	fsc.fields = append(fsc.fields, fields...)
	selbuild := &FnetSubCategory2Select{FnetSubCategory2Query: fsc}
	selbuild.label = fnetsubcategory2.Label
	selbuild.flds, selbuild.scan = &fsc.fields, selbuild.Scan
	return selbuild
}

func (fsc *FnetSubCategory2Query) prepareQuery(ctx context.Context) error {
	for _, f := range fsc.fields {
		if !fnetsubcategory2.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fsc.path != nil {
		prev, err := fsc.path(ctx)
		if err != nil {
			return err
		}
		fsc.sql = prev
	}
	return nil
}

func (fsc *FnetSubCategory2Query) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FnetSubCategory2, error) {
	var (
		nodes       = []*FnetSubCategory2{}
		_spec       = fsc.querySpec()
		loadedTypes = [1]bool{
			fsc.withDocuments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*FnetSubCategory2).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &FnetSubCategory2{config: fsc.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fsc.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fsc.withDocuments; query != nil {
		if err := fsc.loadDocuments(ctx, query, nodes,
			func(n *FnetSubCategory2) { n.Edges.Documents = []*FnetDocument{} },
			func(n *FnetSubCategory2, e *FnetDocument) { n.Edges.Documents = append(n.Edges.Documents, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fsc *FnetSubCategory2Query) loadDocuments(ctx context.Context, query *FnetDocumentQuery, nodes []*FnetSubCategory2, init func(*FnetSubCategory2), assign func(*FnetSubCategory2, *FnetDocument)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*FnetSubCategory2)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.FnetDocument(func(s *sql.Selector) {
		s.Where(sql.InValues(fnetsubcategory2.DocumentsColumn, fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.sub_category2_id
		if fk == nil {
			return fmt.Errorf(`foreign-key "sub_category2_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sub_category2_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fsc *FnetSubCategory2Query) sqlCount(ctx context.Context) (int, error) {
	_spec := fsc.querySpec()
	_spec.Node.Columns = fsc.fields
	if len(fsc.fields) > 0 {
		_spec.Unique = fsc.unique != nil && *fsc.unique
	}
	return sqlgraph.CountNodes(ctx, fsc.driver, _spec)
}

func (fsc *FnetSubCategory2Query) sqlExist(ctx context.Context) (bool, error) {
	n, err := fsc.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (fsc *FnetSubCategory2Query) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fnetsubcategory2.Table,
			Columns: fnetsubcategory2.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fnetsubcategory2.FieldID,
			},
		},
		From:   fsc.sql,
		Unique: true,
	}
	if unique := fsc.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fsc.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fnetsubcategory2.FieldID)
		for i := range fields {
			if fields[i] != fnetsubcategory2.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fsc.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fsc.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fsc.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fsc.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fsc *FnetSubCategory2Query) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fsc.driver.Dialect())
	t1 := builder.Table(fnetsubcategory2.Table)
	columns := fsc.fields
	if len(columns) == 0 {
		columns = fnetsubcategory2.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fsc.sql != nil {
		selector = fsc.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fsc.unique != nil && *fsc.unique {
		selector.Distinct()
	}
	for _, p := range fsc.predicates {
		p(selector)
	}
	for _, p := range fsc.order {
		p(selector)
	}
	if offset := fsc.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fsc.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FnetSubCategory2GroupBy is the group-by builder for FnetSubCategory2 entities.
type FnetSubCategory2GroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fscb *FnetSubCategory2GroupBy) Aggregate(fns ...AggregateFunc) *FnetSubCategory2GroupBy {
	fscb.fns = append(fscb.fns, fns...)
	return fscb
}

// Scan applies the group-by query and scans the result into the given value.
func (fscb *FnetSubCategory2GroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := fscb.path(ctx)
	if err != nil {
		return err
	}
	fscb.sql = query
	return fscb.sqlScan(ctx, v)
}

func (fscb *FnetSubCategory2GroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fscb.fields {
		if !fnetsubcategory2.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := fscb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fscb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fscb *FnetSubCategory2GroupBy) sqlQuery() *sql.Selector {
	selector := fscb.sql.Select()
	aggregation := make([]string, 0, len(fscb.fns))
	for _, fn := range fscb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(fscb.fields)+len(fscb.fns))
		for _, f := range fscb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(fscb.fields...)...)
}

// FnetSubCategory2Select is the builder for selecting fields of FnetSubCategory2 entities.
type FnetSubCategory2Select struct {
	*FnetSubCategory2Query
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (fsc *FnetSubCategory2Select) Scan(ctx context.Context, v interface{}) error {
	if err := fsc.prepareQuery(ctx); err != nil {
		return err
	}
	fsc.sql = fsc.FnetSubCategory2Query.sqlQuery(ctx)
	return fsc.sqlScan(ctx, v)
}

func (fsc *FnetSubCategory2Select) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := fsc.sql.Query()
	if err := fsc.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
