// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lenon/gofii/ent/fnetcategory"
	"github.com/lenon/gofii/ent/fnetdocument"
	"github.com/lenon/gofii/ent/fnetsubcategory1"
	"github.com/lenon/gofii/ent/fnetsubcategory2"
	"github.com/lenon/gofii/ent/predicate"
)

// FnetDocumentUpdate is the builder for updating FnetDocument entities.
type FnetDocumentUpdate struct {
	config
	hooks    []Hook
	mutation *FnetDocumentMutation
}

// Where appends a list predicates to the FnetDocumentUpdate builder.
func (fdu *FnetDocumentUpdate) Where(ps ...predicate.FnetDocument) *FnetDocumentUpdate {
	fdu.mutation.Where(ps...)
	return fdu
}

// SetAdditionalInformation sets the "additional_information" field.
func (fdu *FnetDocumentUpdate) SetAdditionalInformation(s string) *FnetDocumentUpdate {
	fdu.mutation.SetAdditionalInformation(s)
	return fdu
}

// SetNillableAdditionalInformation sets the "additional_information" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableAdditionalInformation(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetAdditionalInformation(*s)
	}
	return fdu
}

// ClearAdditionalInformation clears the value of the "additional_information" field.
func (fdu *FnetDocumentUpdate) ClearAdditionalInformation() *FnetDocumentUpdate {
	fdu.mutation.ClearAdditionalInformation()
	return fdu
}

// SetCategoryStr sets the "category_str" field.
func (fdu *FnetDocumentUpdate) SetCategoryStr(s string) *FnetDocumentUpdate {
	fdu.mutation.SetCategoryStr(s)
	return fdu
}

// SetNillableCategoryStr sets the "category_str" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableCategoryStr(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetCategoryStr(*s)
	}
	return fdu
}

// SetFundDescription sets the "fund_description" field.
func (fdu *FnetDocumentUpdate) SetFundDescription(s string) *FnetDocumentUpdate {
	fdu.mutation.SetFundDescription(s)
	return fdu
}

// SetNillableFundDescription sets the "fund_description" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableFundDescription(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetFundDescription(*s)
	}
	return fdu
}

// SetFundMarketName sets the "fund_market_name" field.
func (fdu *FnetDocumentUpdate) SetFundMarketName(s string) *FnetDocumentUpdate {
	fdu.mutation.SetFundMarketName(s)
	return fdu
}

// SetNillableFundMarketName sets the "fund_market_name" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableFundMarketName(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetFundMarketName(*s)
	}
	return fdu
}

// ClearFundMarketName clears the value of the "fund_market_name" field.
func (fdu *FnetDocumentUpdate) ClearFundMarketName() *FnetDocumentUpdate {
	fdu.mutation.ClearFundMarketName()
	return fdu
}

// SetHighPriority sets the "high_priority" field.
func (fdu *FnetDocumentUpdate) SetHighPriority(b bool) *FnetDocumentUpdate {
	fdu.mutation.SetHighPriority(b)
	return fdu
}

// SetNillableHighPriority sets the "high_priority" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableHighPriority(b *bool) *FnetDocumentUpdate {
	if b != nil {
		fdu.SetHighPriority(*b)
	}
	return fdu
}

// SetReferenceDate sets the "reference_date" field.
func (fdu *FnetDocumentUpdate) SetReferenceDate(t time.Time) *FnetDocumentUpdate {
	fdu.mutation.SetReferenceDate(t)
	return fdu
}

// SetNillableReferenceDate sets the "reference_date" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableReferenceDate(t *time.Time) *FnetDocumentUpdate {
	if t != nil {
		fdu.SetReferenceDate(*t)
	}
	return fdu
}

// SetReferenceDateFormat sets the "reference_date_format" field.
func (fdu *FnetDocumentUpdate) SetReferenceDateFormat(s string) *FnetDocumentUpdate {
	fdu.mutation.SetReferenceDateFormat(s)
	return fdu
}

// SetNillableReferenceDateFormat sets the "reference_date_format" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableReferenceDateFormat(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetReferenceDateFormat(*s)
	}
	return fdu
}

// SetReferenceDateStr sets the "reference_date_str" field.
func (fdu *FnetDocumentUpdate) SetReferenceDateStr(s string) *FnetDocumentUpdate {
	fdu.mutation.SetReferenceDateStr(s)
	return fdu
}

// SetNillableReferenceDateStr sets the "reference_date_str" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableReferenceDateStr(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetReferenceDateStr(*s)
	}
	return fdu
}

// SetReviewed sets the "reviewed" field.
func (fdu *FnetDocumentUpdate) SetReviewed(s string) *FnetDocumentUpdate {
	fdu.mutation.SetReviewed(s)
	return fdu
}

// SetNillableReviewed sets the "reviewed" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableReviewed(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetReviewed(*s)
	}
	return fdu
}

// SetStatus sets the "status" field.
func (fdu *FnetDocumentUpdate) SetStatus(s string) *FnetDocumentUpdate {
	fdu.mutation.SetStatus(s)
	return fdu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableStatus(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetStatus(*s)
	}
	return fdu
}

// SetSubCategory1Str sets the "sub_category1_str" field.
func (fdu *FnetDocumentUpdate) SetSubCategory1Str(s string) *FnetDocumentUpdate {
	fdu.mutation.SetSubCategory1Str(s)
	return fdu
}

// SetNillableSubCategory1Str sets the "sub_category1_str" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubCategory1Str(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetSubCategory1Str(*s)
	}
	return fdu
}

// ClearSubCategory1Str clears the value of the "sub_category1_str" field.
func (fdu *FnetDocumentUpdate) ClearSubCategory1Str() *FnetDocumentUpdate {
	fdu.mutation.ClearSubCategory1Str()
	return fdu
}

// SetSubCategory2Str sets the "sub_category2_str" field.
func (fdu *FnetDocumentUpdate) SetSubCategory2Str(s string) *FnetDocumentUpdate {
	fdu.mutation.SetSubCategory2Str(s)
	return fdu
}

// SetNillableSubCategory2Str sets the "sub_category2_str" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubCategory2Str(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetSubCategory2Str(*s)
	}
	return fdu
}

// ClearSubCategory2Str clears the value of the "sub_category2_str" field.
func (fdu *FnetDocumentUpdate) ClearSubCategory2Str() *FnetDocumentUpdate {
	fdu.mutation.ClearSubCategory2Str()
	return fdu
}

// SetSubmissionDate sets the "submission_date" field.
func (fdu *FnetDocumentUpdate) SetSubmissionDate(t time.Time) *FnetDocumentUpdate {
	fdu.mutation.SetSubmissionDate(t)
	return fdu
}

// SetNillableSubmissionDate sets the "submission_date" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubmissionDate(t *time.Time) *FnetDocumentUpdate {
	if t != nil {
		fdu.SetSubmissionDate(*t)
	}
	return fdu
}

// SetSubmissionDateStr sets the "submission_date_str" field.
func (fdu *FnetDocumentUpdate) SetSubmissionDateStr(s string) *FnetDocumentUpdate {
	fdu.mutation.SetSubmissionDateStr(s)
	return fdu
}

// SetNillableSubmissionDateStr sets the "submission_date_str" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubmissionDateStr(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetSubmissionDateStr(*s)
	}
	return fdu
}

// SetSubmissionMethod sets the "submission_method" field.
func (fdu *FnetDocumentUpdate) SetSubmissionMethod(s string) *FnetDocumentUpdate {
	fdu.mutation.SetSubmissionMethod(s)
	return fdu
}

// SetNillableSubmissionMethod sets the "submission_method" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubmissionMethod(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetSubmissionMethod(*s)
	}
	return fdu
}

// SetSubmissionMethodDescription sets the "submission_method_description" field.
func (fdu *FnetDocumentUpdate) SetSubmissionMethodDescription(s string) *FnetDocumentUpdate {
	fdu.mutation.SetSubmissionMethodDescription(s)
	return fdu
}

// SetNillableSubmissionMethodDescription sets the "submission_method_description" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubmissionMethodDescription(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetSubmissionMethodDescription(*s)
	}
	return fdu
}

// SetSubmissionStatus sets the "submission_status" field.
func (fdu *FnetDocumentUpdate) SetSubmissionStatus(s string) *FnetDocumentUpdate {
	fdu.mutation.SetSubmissionStatus(s)
	return fdu
}

// SetNillableSubmissionStatus sets the "submission_status" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubmissionStatus(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetSubmissionStatus(*s)
	}
	return fdu
}

// SetSubmissionStatusDescription sets the "submission_status_description" field.
func (fdu *FnetDocumentUpdate) SetSubmissionStatusDescription(s string) *FnetDocumentUpdate {
	fdu.mutation.SetSubmissionStatusDescription(s)
	return fdu
}

// SetNillableSubmissionStatusDescription sets the "submission_status_description" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubmissionStatusDescription(s *string) *FnetDocumentUpdate {
	if s != nil {
		fdu.SetSubmissionStatusDescription(*s)
	}
	return fdu
}

// SetVersion sets the "version" field.
func (fdu *FnetDocumentUpdate) SetVersion(i int) *FnetDocumentUpdate {
	fdu.mutation.ResetVersion()
	fdu.mutation.SetVersion(i)
	return fdu
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableVersion(i *int) *FnetDocumentUpdate {
	if i != nil {
		fdu.SetVersion(*i)
	}
	return fdu
}

// AddVersion adds i to the "version" field.
func (fdu *FnetDocumentUpdate) AddVersion(i int) *FnetDocumentUpdate {
	fdu.mutation.AddVersion(i)
	return fdu
}

// SetCategoryID sets the "category" edge to the FnetCategory entity by ID.
func (fdu *FnetDocumentUpdate) SetCategoryID(id int) *FnetDocumentUpdate {
	fdu.mutation.SetCategoryID(id)
	return fdu
}

// SetCategory sets the "category" edge to the FnetCategory entity.
func (fdu *FnetDocumentUpdate) SetCategory(f *FnetCategory) *FnetDocumentUpdate {
	return fdu.SetCategoryID(f.ID)
}

// SetSubCategory1ID sets the "sub_category1" edge to the FnetSubCategory1 entity by ID.
func (fdu *FnetDocumentUpdate) SetSubCategory1ID(id int) *FnetDocumentUpdate {
	fdu.mutation.SetSubCategory1ID(id)
	return fdu
}

// SetNillableSubCategory1ID sets the "sub_category1" edge to the FnetSubCategory1 entity by ID if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubCategory1ID(id *int) *FnetDocumentUpdate {
	if id != nil {
		fdu = fdu.SetSubCategory1ID(*id)
	}
	return fdu
}

// SetSubCategory1 sets the "sub_category1" edge to the FnetSubCategory1 entity.
func (fdu *FnetDocumentUpdate) SetSubCategory1(f *FnetSubCategory1) *FnetDocumentUpdate {
	return fdu.SetSubCategory1ID(f.ID)
}

// SetSubCategory2ID sets the "sub_category2" edge to the FnetSubCategory2 entity by ID.
func (fdu *FnetDocumentUpdate) SetSubCategory2ID(id int) *FnetDocumentUpdate {
	fdu.mutation.SetSubCategory2ID(id)
	return fdu
}

// SetNillableSubCategory2ID sets the "sub_category2" edge to the FnetSubCategory2 entity by ID if the given value is not nil.
func (fdu *FnetDocumentUpdate) SetNillableSubCategory2ID(id *int) *FnetDocumentUpdate {
	if id != nil {
		fdu = fdu.SetSubCategory2ID(*id)
	}
	return fdu
}

// SetSubCategory2 sets the "sub_category2" edge to the FnetSubCategory2 entity.
func (fdu *FnetDocumentUpdate) SetSubCategory2(f *FnetSubCategory2) *FnetDocumentUpdate {
	return fdu.SetSubCategory2ID(f.ID)
}

// Mutation returns the FnetDocumentMutation object of the builder.
func (fdu *FnetDocumentUpdate) Mutation() *FnetDocumentMutation {
	return fdu.mutation
}

// ClearCategory clears the "category" edge to the FnetCategory entity.
func (fdu *FnetDocumentUpdate) ClearCategory() *FnetDocumentUpdate {
	fdu.mutation.ClearCategory()
	return fdu
}

// ClearSubCategory1 clears the "sub_category1" edge to the FnetSubCategory1 entity.
func (fdu *FnetDocumentUpdate) ClearSubCategory1() *FnetDocumentUpdate {
	fdu.mutation.ClearSubCategory1()
	return fdu
}

// ClearSubCategory2 clears the "sub_category2" edge to the FnetSubCategory2 entity.
func (fdu *FnetDocumentUpdate) ClearSubCategory2() *FnetDocumentUpdate {
	fdu.mutation.ClearSubCategory2()
	return fdu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fdu *FnetDocumentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fdu.sqlSave, fdu.mutation, fdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fdu *FnetDocumentUpdate) SaveX(ctx context.Context) int {
	affected, err := fdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fdu *FnetDocumentUpdate) Exec(ctx context.Context) error {
	_, err := fdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fdu *FnetDocumentUpdate) ExecX(ctx context.Context) {
	if err := fdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fdu *FnetDocumentUpdate) check() error {
	if v, ok := fdu.mutation.CategoryStr(); ok {
		if err := fnetdocument.CategoryStrValidator(v); err != nil {
			return &ValidationError{Name: "category_str", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.category_str": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.FundDescription(); ok {
		if err := fnetdocument.FundDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "fund_description", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.fund_description": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.ReferenceDateFormat(); ok {
		if err := fnetdocument.ReferenceDateFormatValidator(v); err != nil {
			return &ValidationError{Name: "reference_date_format", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.reference_date_format": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.ReferenceDateStr(); ok {
		if err := fnetdocument.ReferenceDateStrValidator(v); err != nil {
			return &ValidationError{Name: "reference_date_str", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.reference_date_str": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.Reviewed(); ok {
		if err := fnetdocument.ReviewedValidator(v); err != nil {
			return &ValidationError{Name: "reviewed", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.reviewed": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.Status(); ok {
		if err := fnetdocument.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.status": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.SubmissionDateStr(); ok {
		if err := fnetdocument.SubmissionDateStrValidator(v); err != nil {
			return &ValidationError{Name: "submission_date_str", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_date_str": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.SubmissionMethod(); ok {
		if err := fnetdocument.SubmissionMethodValidator(v); err != nil {
			return &ValidationError{Name: "submission_method", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_method": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.SubmissionMethodDescription(); ok {
		if err := fnetdocument.SubmissionMethodDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "submission_method_description", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_method_description": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.SubmissionStatus(); ok {
		if err := fnetdocument.SubmissionStatusValidator(v); err != nil {
			return &ValidationError{Name: "submission_status", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_status": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.SubmissionStatusDescription(); ok {
		if err := fnetdocument.SubmissionStatusDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "submission_status_description", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_status_description": %w`, err)}
		}
	}
	if v, ok := fdu.mutation.Version(); ok {
		if err := fnetdocument.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.version": %w`, err)}
		}
	}
	if _, ok := fdu.mutation.CategoryID(); fdu.mutation.CategoryCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "FnetDocument.category"`)
	}
	return nil
}

func (fdu *FnetDocumentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(fnetdocument.Table, fnetdocument.Columns, sqlgraph.NewFieldSpec(fnetdocument.FieldID, field.TypeInt))
	if ps := fdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fdu.mutation.AdditionalInformation(); ok {
		_spec.SetField(fnetdocument.FieldAdditionalInformation, field.TypeString, value)
	}
	if fdu.mutation.AdditionalInformationCleared() {
		_spec.ClearField(fnetdocument.FieldAdditionalInformation, field.TypeString)
	}
	if value, ok := fdu.mutation.CategoryStr(); ok {
		_spec.SetField(fnetdocument.FieldCategoryStr, field.TypeString, value)
	}
	if value, ok := fdu.mutation.FundDescription(); ok {
		_spec.SetField(fnetdocument.FieldFundDescription, field.TypeString, value)
	}
	if value, ok := fdu.mutation.FundMarketName(); ok {
		_spec.SetField(fnetdocument.FieldFundMarketName, field.TypeString, value)
	}
	if fdu.mutation.FundMarketNameCleared() {
		_spec.ClearField(fnetdocument.FieldFundMarketName, field.TypeString)
	}
	if value, ok := fdu.mutation.HighPriority(); ok {
		_spec.SetField(fnetdocument.FieldHighPriority, field.TypeBool, value)
	}
	if value, ok := fdu.mutation.ReferenceDate(); ok {
		_spec.SetField(fnetdocument.FieldReferenceDate, field.TypeTime, value)
	}
	if value, ok := fdu.mutation.ReferenceDateFormat(); ok {
		_spec.SetField(fnetdocument.FieldReferenceDateFormat, field.TypeString, value)
	}
	if value, ok := fdu.mutation.ReferenceDateStr(); ok {
		_spec.SetField(fnetdocument.FieldReferenceDateStr, field.TypeString, value)
	}
	if value, ok := fdu.mutation.Reviewed(); ok {
		_spec.SetField(fnetdocument.FieldReviewed, field.TypeString, value)
	}
	if value, ok := fdu.mutation.Status(); ok {
		_spec.SetField(fnetdocument.FieldStatus, field.TypeString, value)
	}
	if value, ok := fdu.mutation.SubCategory1Str(); ok {
		_spec.SetField(fnetdocument.FieldSubCategory1Str, field.TypeString, value)
	}
	if fdu.mutation.SubCategory1StrCleared() {
		_spec.ClearField(fnetdocument.FieldSubCategory1Str, field.TypeString)
	}
	if value, ok := fdu.mutation.SubCategory2Str(); ok {
		_spec.SetField(fnetdocument.FieldSubCategory2Str, field.TypeString, value)
	}
	if fdu.mutation.SubCategory2StrCleared() {
		_spec.ClearField(fnetdocument.FieldSubCategory2Str, field.TypeString)
	}
	if value, ok := fdu.mutation.SubmissionDate(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionDate, field.TypeTime, value)
	}
	if value, ok := fdu.mutation.SubmissionDateStr(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionDateStr, field.TypeString, value)
	}
	if value, ok := fdu.mutation.SubmissionMethod(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionMethod, field.TypeString, value)
	}
	if value, ok := fdu.mutation.SubmissionMethodDescription(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionMethodDescription, field.TypeString, value)
	}
	if value, ok := fdu.mutation.SubmissionStatus(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionStatus, field.TypeString, value)
	}
	if value, ok := fdu.mutation.SubmissionStatusDescription(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionStatusDescription, field.TypeString, value)
	}
	if value, ok := fdu.mutation.Version(); ok {
		_spec.SetField(fnetdocument.FieldVersion, field.TypeInt, value)
	}
	if value, ok := fdu.mutation.AddedVersion(); ok {
		_spec.AddField(fnetdocument.FieldVersion, field.TypeInt, value)
	}
	if fdu.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.CategoryTable,
			Columns: []string{fnetdocument.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetcategory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fdu.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.CategoryTable,
			Columns: []string{fnetdocument.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fdu.mutation.SubCategory1Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.SubCategory1Table,
			Columns: []string{fnetdocument.SubCategory1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetsubcategory1.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fdu.mutation.SubCategory1IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.SubCategory1Table,
			Columns: []string{fnetdocument.SubCategory1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetsubcategory1.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fdu.mutation.SubCategory2Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.SubCategory2Table,
			Columns: []string{fnetdocument.SubCategory2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetsubcategory2.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fdu.mutation.SubCategory2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.SubCategory2Table,
			Columns: []string{fnetdocument.SubCategory2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetsubcategory2.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fnetdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fdu.mutation.done = true
	return n, nil
}

// FnetDocumentUpdateOne is the builder for updating a single FnetDocument entity.
type FnetDocumentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FnetDocumentMutation
}

// SetAdditionalInformation sets the "additional_information" field.
func (fduo *FnetDocumentUpdateOne) SetAdditionalInformation(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetAdditionalInformation(s)
	return fduo
}

// SetNillableAdditionalInformation sets the "additional_information" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableAdditionalInformation(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetAdditionalInformation(*s)
	}
	return fduo
}

// ClearAdditionalInformation clears the value of the "additional_information" field.
func (fduo *FnetDocumentUpdateOne) ClearAdditionalInformation() *FnetDocumentUpdateOne {
	fduo.mutation.ClearAdditionalInformation()
	return fduo
}

// SetCategoryStr sets the "category_str" field.
func (fduo *FnetDocumentUpdateOne) SetCategoryStr(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetCategoryStr(s)
	return fduo
}

// SetNillableCategoryStr sets the "category_str" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableCategoryStr(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetCategoryStr(*s)
	}
	return fduo
}

// SetFundDescription sets the "fund_description" field.
func (fduo *FnetDocumentUpdateOne) SetFundDescription(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetFundDescription(s)
	return fduo
}

// SetNillableFundDescription sets the "fund_description" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableFundDescription(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetFundDescription(*s)
	}
	return fduo
}

// SetFundMarketName sets the "fund_market_name" field.
func (fduo *FnetDocumentUpdateOne) SetFundMarketName(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetFundMarketName(s)
	return fduo
}

// SetNillableFundMarketName sets the "fund_market_name" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableFundMarketName(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetFundMarketName(*s)
	}
	return fduo
}

// ClearFundMarketName clears the value of the "fund_market_name" field.
func (fduo *FnetDocumentUpdateOne) ClearFundMarketName() *FnetDocumentUpdateOne {
	fduo.mutation.ClearFundMarketName()
	return fduo
}

// SetHighPriority sets the "high_priority" field.
func (fduo *FnetDocumentUpdateOne) SetHighPriority(b bool) *FnetDocumentUpdateOne {
	fduo.mutation.SetHighPriority(b)
	return fduo
}

// SetNillableHighPriority sets the "high_priority" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableHighPriority(b *bool) *FnetDocumentUpdateOne {
	if b != nil {
		fduo.SetHighPriority(*b)
	}
	return fduo
}

// SetReferenceDate sets the "reference_date" field.
func (fduo *FnetDocumentUpdateOne) SetReferenceDate(t time.Time) *FnetDocumentUpdateOne {
	fduo.mutation.SetReferenceDate(t)
	return fduo
}

// SetNillableReferenceDate sets the "reference_date" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableReferenceDate(t *time.Time) *FnetDocumentUpdateOne {
	if t != nil {
		fduo.SetReferenceDate(*t)
	}
	return fduo
}

// SetReferenceDateFormat sets the "reference_date_format" field.
func (fduo *FnetDocumentUpdateOne) SetReferenceDateFormat(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetReferenceDateFormat(s)
	return fduo
}

// SetNillableReferenceDateFormat sets the "reference_date_format" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableReferenceDateFormat(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetReferenceDateFormat(*s)
	}
	return fduo
}

// SetReferenceDateStr sets the "reference_date_str" field.
func (fduo *FnetDocumentUpdateOne) SetReferenceDateStr(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetReferenceDateStr(s)
	return fduo
}

// SetNillableReferenceDateStr sets the "reference_date_str" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableReferenceDateStr(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetReferenceDateStr(*s)
	}
	return fduo
}

// SetReviewed sets the "reviewed" field.
func (fduo *FnetDocumentUpdateOne) SetReviewed(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetReviewed(s)
	return fduo
}

// SetNillableReviewed sets the "reviewed" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableReviewed(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetReviewed(*s)
	}
	return fduo
}

// SetStatus sets the "status" field.
func (fduo *FnetDocumentUpdateOne) SetStatus(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetStatus(s)
	return fduo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableStatus(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetStatus(*s)
	}
	return fduo
}

// SetSubCategory1Str sets the "sub_category1_str" field.
func (fduo *FnetDocumentUpdateOne) SetSubCategory1Str(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubCategory1Str(s)
	return fduo
}

// SetNillableSubCategory1Str sets the "sub_category1_str" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubCategory1Str(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetSubCategory1Str(*s)
	}
	return fduo
}

// ClearSubCategory1Str clears the value of the "sub_category1_str" field.
func (fduo *FnetDocumentUpdateOne) ClearSubCategory1Str() *FnetDocumentUpdateOne {
	fduo.mutation.ClearSubCategory1Str()
	return fduo
}

// SetSubCategory2Str sets the "sub_category2_str" field.
func (fduo *FnetDocumentUpdateOne) SetSubCategory2Str(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubCategory2Str(s)
	return fduo
}

// SetNillableSubCategory2Str sets the "sub_category2_str" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubCategory2Str(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetSubCategory2Str(*s)
	}
	return fduo
}

// ClearSubCategory2Str clears the value of the "sub_category2_str" field.
func (fduo *FnetDocumentUpdateOne) ClearSubCategory2Str() *FnetDocumentUpdateOne {
	fduo.mutation.ClearSubCategory2Str()
	return fduo
}

// SetSubmissionDate sets the "submission_date" field.
func (fduo *FnetDocumentUpdateOne) SetSubmissionDate(t time.Time) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubmissionDate(t)
	return fduo
}

// SetNillableSubmissionDate sets the "submission_date" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubmissionDate(t *time.Time) *FnetDocumentUpdateOne {
	if t != nil {
		fduo.SetSubmissionDate(*t)
	}
	return fduo
}

// SetSubmissionDateStr sets the "submission_date_str" field.
func (fduo *FnetDocumentUpdateOne) SetSubmissionDateStr(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubmissionDateStr(s)
	return fduo
}

// SetNillableSubmissionDateStr sets the "submission_date_str" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubmissionDateStr(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetSubmissionDateStr(*s)
	}
	return fduo
}

// SetSubmissionMethod sets the "submission_method" field.
func (fduo *FnetDocumentUpdateOne) SetSubmissionMethod(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubmissionMethod(s)
	return fduo
}

// SetNillableSubmissionMethod sets the "submission_method" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubmissionMethod(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetSubmissionMethod(*s)
	}
	return fduo
}

// SetSubmissionMethodDescription sets the "submission_method_description" field.
func (fduo *FnetDocumentUpdateOne) SetSubmissionMethodDescription(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubmissionMethodDescription(s)
	return fduo
}

// SetNillableSubmissionMethodDescription sets the "submission_method_description" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubmissionMethodDescription(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetSubmissionMethodDescription(*s)
	}
	return fduo
}

// SetSubmissionStatus sets the "submission_status" field.
func (fduo *FnetDocumentUpdateOne) SetSubmissionStatus(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubmissionStatus(s)
	return fduo
}

// SetNillableSubmissionStatus sets the "submission_status" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubmissionStatus(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetSubmissionStatus(*s)
	}
	return fduo
}

// SetSubmissionStatusDescription sets the "submission_status_description" field.
func (fduo *FnetDocumentUpdateOne) SetSubmissionStatusDescription(s string) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubmissionStatusDescription(s)
	return fduo
}

// SetNillableSubmissionStatusDescription sets the "submission_status_description" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubmissionStatusDescription(s *string) *FnetDocumentUpdateOne {
	if s != nil {
		fduo.SetSubmissionStatusDescription(*s)
	}
	return fduo
}

// SetVersion sets the "version" field.
func (fduo *FnetDocumentUpdateOne) SetVersion(i int) *FnetDocumentUpdateOne {
	fduo.mutation.ResetVersion()
	fduo.mutation.SetVersion(i)
	return fduo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableVersion(i *int) *FnetDocumentUpdateOne {
	if i != nil {
		fduo.SetVersion(*i)
	}
	return fduo
}

// AddVersion adds i to the "version" field.
func (fduo *FnetDocumentUpdateOne) AddVersion(i int) *FnetDocumentUpdateOne {
	fduo.mutation.AddVersion(i)
	return fduo
}

// SetCategoryID sets the "category" edge to the FnetCategory entity by ID.
func (fduo *FnetDocumentUpdateOne) SetCategoryID(id int) *FnetDocumentUpdateOne {
	fduo.mutation.SetCategoryID(id)
	return fduo
}

// SetCategory sets the "category" edge to the FnetCategory entity.
func (fduo *FnetDocumentUpdateOne) SetCategory(f *FnetCategory) *FnetDocumentUpdateOne {
	return fduo.SetCategoryID(f.ID)
}

// SetSubCategory1ID sets the "sub_category1" edge to the FnetSubCategory1 entity by ID.
func (fduo *FnetDocumentUpdateOne) SetSubCategory1ID(id int) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubCategory1ID(id)
	return fduo
}

// SetNillableSubCategory1ID sets the "sub_category1" edge to the FnetSubCategory1 entity by ID if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubCategory1ID(id *int) *FnetDocumentUpdateOne {
	if id != nil {
		fduo = fduo.SetSubCategory1ID(*id)
	}
	return fduo
}

// SetSubCategory1 sets the "sub_category1" edge to the FnetSubCategory1 entity.
func (fduo *FnetDocumentUpdateOne) SetSubCategory1(f *FnetSubCategory1) *FnetDocumentUpdateOne {
	return fduo.SetSubCategory1ID(f.ID)
}

// SetSubCategory2ID sets the "sub_category2" edge to the FnetSubCategory2 entity by ID.
func (fduo *FnetDocumentUpdateOne) SetSubCategory2ID(id int) *FnetDocumentUpdateOne {
	fduo.mutation.SetSubCategory2ID(id)
	return fduo
}

// SetNillableSubCategory2ID sets the "sub_category2" edge to the FnetSubCategory2 entity by ID if the given value is not nil.
func (fduo *FnetDocumentUpdateOne) SetNillableSubCategory2ID(id *int) *FnetDocumentUpdateOne {
	if id != nil {
		fduo = fduo.SetSubCategory2ID(*id)
	}
	return fduo
}

// SetSubCategory2 sets the "sub_category2" edge to the FnetSubCategory2 entity.
func (fduo *FnetDocumentUpdateOne) SetSubCategory2(f *FnetSubCategory2) *FnetDocumentUpdateOne {
	return fduo.SetSubCategory2ID(f.ID)
}

// Mutation returns the FnetDocumentMutation object of the builder.
func (fduo *FnetDocumentUpdateOne) Mutation() *FnetDocumentMutation {
	return fduo.mutation
}

// ClearCategory clears the "category" edge to the FnetCategory entity.
func (fduo *FnetDocumentUpdateOne) ClearCategory() *FnetDocumentUpdateOne {
	fduo.mutation.ClearCategory()
	return fduo
}

// ClearSubCategory1 clears the "sub_category1" edge to the FnetSubCategory1 entity.
func (fduo *FnetDocumentUpdateOne) ClearSubCategory1() *FnetDocumentUpdateOne {
	fduo.mutation.ClearSubCategory1()
	return fduo
}

// ClearSubCategory2 clears the "sub_category2" edge to the FnetSubCategory2 entity.
func (fduo *FnetDocumentUpdateOne) ClearSubCategory2() *FnetDocumentUpdateOne {
	fduo.mutation.ClearSubCategory2()
	return fduo
}

// Where appends a list predicates to the FnetDocumentUpdate builder.
func (fduo *FnetDocumentUpdateOne) Where(ps ...predicate.FnetDocument) *FnetDocumentUpdateOne {
	fduo.mutation.Where(ps...)
	return fduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fduo *FnetDocumentUpdateOne) Select(field string, fields ...string) *FnetDocumentUpdateOne {
	fduo.fields = append([]string{field}, fields...)
	return fduo
}

// Save executes the query and returns the updated FnetDocument entity.
func (fduo *FnetDocumentUpdateOne) Save(ctx context.Context) (*FnetDocument, error) {
	return withHooks(ctx, fduo.sqlSave, fduo.mutation, fduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fduo *FnetDocumentUpdateOne) SaveX(ctx context.Context) *FnetDocument {
	node, err := fduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fduo *FnetDocumentUpdateOne) Exec(ctx context.Context) error {
	_, err := fduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fduo *FnetDocumentUpdateOne) ExecX(ctx context.Context) {
	if err := fduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fduo *FnetDocumentUpdateOne) check() error {
	if v, ok := fduo.mutation.CategoryStr(); ok {
		if err := fnetdocument.CategoryStrValidator(v); err != nil {
			return &ValidationError{Name: "category_str", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.category_str": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.FundDescription(); ok {
		if err := fnetdocument.FundDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "fund_description", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.fund_description": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.ReferenceDateFormat(); ok {
		if err := fnetdocument.ReferenceDateFormatValidator(v); err != nil {
			return &ValidationError{Name: "reference_date_format", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.reference_date_format": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.ReferenceDateStr(); ok {
		if err := fnetdocument.ReferenceDateStrValidator(v); err != nil {
			return &ValidationError{Name: "reference_date_str", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.reference_date_str": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.Reviewed(); ok {
		if err := fnetdocument.ReviewedValidator(v); err != nil {
			return &ValidationError{Name: "reviewed", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.reviewed": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.Status(); ok {
		if err := fnetdocument.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.status": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.SubmissionDateStr(); ok {
		if err := fnetdocument.SubmissionDateStrValidator(v); err != nil {
			return &ValidationError{Name: "submission_date_str", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_date_str": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.SubmissionMethod(); ok {
		if err := fnetdocument.SubmissionMethodValidator(v); err != nil {
			return &ValidationError{Name: "submission_method", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_method": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.SubmissionMethodDescription(); ok {
		if err := fnetdocument.SubmissionMethodDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "submission_method_description", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_method_description": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.SubmissionStatus(); ok {
		if err := fnetdocument.SubmissionStatusValidator(v); err != nil {
			return &ValidationError{Name: "submission_status", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_status": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.SubmissionStatusDescription(); ok {
		if err := fnetdocument.SubmissionStatusDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "submission_status_description", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.submission_status_description": %w`, err)}
		}
	}
	if v, ok := fduo.mutation.Version(); ok {
		if err := fnetdocument.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "FnetDocument.version": %w`, err)}
		}
	}
	if _, ok := fduo.mutation.CategoryID(); fduo.mutation.CategoryCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "FnetDocument.category"`)
	}
	return nil
}

func (fduo *FnetDocumentUpdateOne) sqlSave(ctx context.Context) (_node *FnetDocument, err error) {
	if err := fduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fnetdocument.Table, fnetdocument.Columns, sqlgraph.NewFieldSpec(fnetdocument.FieldID, field.TypeInt))
	id, ok := fduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FnetDocument.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fnetdocument.FieldID)
		for _, f := range fields {
			if !fnetdocument.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fnetdocument.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fduo.mutation.AdditionalInformation(); ok {
		_spec.SetField(fnetdocument.FieldAdditionalInformation, field.TypeString, value)
	}
	if fduo.mutation.AdditionalInformationCleared() {
		_spec.ClearField(fnetdocument.FieldAdditionalInformation, field.TypeString)
	}
	if value, ok := fduo.mutation.CategoryStr(); ok {
		_spec.SetField(fnetdocument.FieldCategoryStr, field.TypeString, value)
	}
	if value, ok := fduo.mutation.FundDescription(); ok {
		_spec.SetField(fnetdocument.FieldFundDescription, field.TypeString, value)
	}
	if value, ok := fduo.mutation.FundMarketName(); ok {
		_spec.SetField(fnetdocument.FieldFundMarketName, field.TypeString, value)
	}
	if fduo.mutation.FundMarketNameCleared() {
		_spec.ClearField(fnetdocument.FieldFundMarketName, field.TypeString)
	}
	if value, ok := fduo.mutation.HighPriority(); ok {
		_spec.SetField(fnetdocument.FieldHighPriority, field.TypeBool, value)
	}
	if value, ok := fduo.mutation.ReferenceDate(); ok {
		_spec.SetField(fnetdocument.FieldReferenceDate, field.TypeTime, value)
	}
	if value, ok := fduo.mutation.ReferenceDateFormat(); ok {
		_spec.SetField(fnetdocument.FieldReferenceDateFormat, field.TypeString, value)
	}
	if value, ok := fduo.mutation.ReferenceDateStr(); ok {
		_spec.SetField(fnetdocument.FieldReferenceDateStr, field.TypeString, value)
	}
	if value, ok := fduo.mutation.Reviewed(); ok {
		_spec.SetField(fnetdocument.FieldReviewed, field.TypeString, value)
	}
	if value, ok := fduo.mutation.Status(); ok {
		_spec.SetField(fnetdocument.FieldStatus, field.TypeString, value)
	}
	if value, ok := fduo.mutation.SubCategory1Str(); ok {
		_spec.SetField(fnetdocument.FieldSubCategory1Str, field.TypeString, value)
	}
	if fduo.mutation.SubCategory1StrCleared() {
		_spec.ClearField(fnetdocument.FieldSubCategory1Str, field.TypeString)
	}
	if value, ok := fduo.mutation.SubCategory2Str(); ok {
		_spec.SetField(fnetdocument.FieldSubCategory2Str, field.TypeString, value)
	}
	if fduo.mutation.SubCategory2StrCleared() {
		_spec.ClearField(fnetdocument.FieldSubCategory2Str, field.TypeString)
	}
	if value, ok := fduo.mutation.SubmissionDate(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionDate, field.TypeTime, value)
	}
	if value, ok := fduo.mutation.SubmissionDateStr(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionDateStr, field.TypeString, value)
	}
	if value, ok := fduo.mutation.SubmissionMethod(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionMethod, field.TypeString, value)
	}
	if value, ok := fduo.mutation.SubmissionMethodDescription(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionMethodDescription, field.TypeString, value)
	}
	if value, ok := fduo.mutation.SubmissionStatus(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionStatus, field.TypeString, value)
	}
	if value, ok := fduo.mutation.SubmissionStatusDescription(); ok {
		_spec.SetField(fnetdocument.FieldSubmissionStatusDescription, field.TypeString, value)
	}
	if value, ok := fduo.mutation.Version(); ok {
		_spec.SetField(fnetdocument.FieldVersion, field.TypeInt, value)
	}
	if value, ok := fduo.mutation.AddedVersion(); ok {
		_spec.AddField(fnetdocument.FieldVersion, field.TypeInt, value)
	}
	if fduo.mutation.CategoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.CategoryTable,
			Columns: []string{fnetdocument.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetcategory.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fduo.mutation.CategoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.CategoryTable,
			Columns: []string{fnetdocument.CategoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetcategory.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fduo.mutation.SubCategory1Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.SubCategory1Table,
			Columns: []string{fnetdocument.SubCategory1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetsubcategory1.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fduo.mutation.SubCategory1IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.SubCategory1Table,
			Columns: []string{fnetdocument.SubCategory1Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetsubcategory1.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if fduo.mutation.SubCategory2Cleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.SubCategory2Table,
			Columns: []string{fnetdocument.SubCategory2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetsubcategory2.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fduo.mutation.SubCategory2IDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   fnetdocument.SubCategory2Table,
			Columns: []string{fnetdocument.SubCategory2Column},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fnetsubcategory2.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FnetDocument{config: fduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fnetdocument.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fduo.mutation.done = true
	return _node, nil
}
