// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lenon/gofii/ent/fnetcategory"
	"github.com/lenon/gofii/ent/predicate"
)

// FnetCategoryDelete is the builder for deleting a FnetCategory entity.
type FnetCategoryDelete struct {
	config
	hooks    []Hook
	mutation *FnetCategoryMutation
}

// Where appends a list predicates to the FnetCategoryDelete builder.
func (fcd *FnetCategoryDelete) Where(ps ...predicate.FnetCategory) *FnetCategoryDelete {
	fcd.mutation.Where(ps...)
	return fcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fcd *FnetCategoryDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(fcd.hooks) == 0 {
		affected, err = fcd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FnetCategoryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fcd.mutation = mutation
			affected, err = fcd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fcd.hooks) - 1; i >= 0; i-- {
			if fcd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = fcd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fcd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcd *FnetCategoryDelete) ExecX(ctx context.Context) int {
	n, err := fcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fcd *FnetCategoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: fnetcategory.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fnetcategory.FieldID,
			},
		},
	}
	if ps := fcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// FnetCategoryDeleteOne is the builder for deleting a single FnetCategory entity.
type FnetCategoryDeleteOne struct {
	fcd *FnetCategoryDelete
}

// Exec executes the deletion query.
func (fcdo *FnetCategoryDeleteOne) Exec(ctx context.Context) error {
	n, err := fcdo.fcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fnetcategory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fcdo *FnetCategoryDeleteOne) ExecX(ctx context.Context) {
	fcdo.fcd.ExecX(ctx)
}
