// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/lenon/gofii/ent/fnetdocument"
	"github.com/lenon/gofii/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fnetdocumentFields := schema.FnetDocument{}.Fields()
	_ = fnetdocumentFields
	// fnetdocumentDescFnetID is the schema descriptor for fnet_id field.
	fnetdocumentDescFnetID := fnetdocumentFields[0].Descriptor()
	// fnetdocument.FnetIDValidator is a validator for the "fnet_id" field. It is called by the builders before save.
	fnetdocument.FnetIDValidator = fnetdocumentDescFnetID.Validators[0].(func(int) error)
	// fnetdocumentDescDocumentCategory is the schema descriptor for document_category field.
	fnetdocumentDescDocumentCategory := fnetdocumentFields[2].Descriptor()
	// fnetdocument.DocumentCategoryValidator is a validator for the "document_category" field. It is called by the builders before save.
	fnetdocument.DocumentCategoryValidator = fnetdocumentDescDocumentCategory.Validators[0].(func(string) error)
	// fnetdocumentDescDocumentStatus is the schema descriptor for document_status field.
	fnetdocumentDescDocumentStatus := fnetdocumentFields[3].Descriptor()
	// fnetdocument.DocumentStatusValidator is a validator for the "document_status" field. It is called by the builders before save.
	fnetdocument.DocumentStatusValidator = fnetdocumentDescDocumentStatus.Validators[0].(func(string) error)
	// fnetdocumentDescFundDescription is the schema descriptor for fund_description field.
	fnetdocumentDescFundDescription := fnetdocumentFields[6].Descriptor()
	// fnetdocument.FundDescriptionValidator is a validator for the "fund_description" field. It is called by the builders before save.
	fnetdocument.FundDescriptionValidator = fnetdocumentDescFundDescription.Validators[0].(func(string) error)
	// fnetdocumentDescReferenceDateFormat is the schema descriptor for reference_date_format field.
	fnetdocumentDescReferenceDateFormat := fnetdocumentFields[9].Descriptor()
	// fnetdocument.ReferenceDateFormatValidator is a validator for the "reference_date_format" field. It is called by the builders before save.
	fnetdocument.ReferenceDateFormatValidator = fnetdocumentDescReferenceDateFormat.Validators[0].(func(string) error)
	// fnetdocumentDescReferenceDate is the schema descriptor for reference_date field.
	fnetdocumentDescReferenceDate := fnetdocumentFields[10].Descriptor()
	// fnetdocument.ReferenceDateValidator is a validator for the "reference_date" field. It is called by the builders before save.
	fnetdocument.ReferenceDateValidator = fnetdocumentDescReferenceDate.Validators[0].(func(string) error)
	// fnetdocumentDescReviewed is the schema descriptor for reviewed field.
	fnetdocumentDescReviewed := fnetdocumentFields[11].Descriptor()
	// fnetdocument.ReviewedValidator is a validator for the "reviewed" field. It is called by the builders before save.
	fnetdocument.ReviewedValidator = fnetdocumentDescReviewed.Validators[0].(func(string) error)
	// fnetdocumentDescStatusDescription is the schema descriptor for status_description field.
	fnetdocumentDescStatusDescription := fnetdocumentFields[12].Descriptor()
	// fnetdocument.StatusDescriptionValidator is a validator for the "status_description" field. It is called by the builders before save.
	fnetdocument.StatusDescriptionValidator = fnetdocumentDescStatusDescription.Validators[0].(func(string) error)
	// fnetdocumentDescStatus is the schema descriptor for status field.
	fnetdocumentDescStatus := fnetdocumentFields[13].Descriptor()
	// fnetdocument.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	fnetdocument.StatusValidator = fnetdocumentDescStatus.Validators[0].(func(string) error)
	// fnetdocumentDescSubmissionDate is the schema descriptor for submission_date field.
	fnetdocumentDescSubmissionDate := fnetdocumentFields[14].Descriptor()
	// fnetdocument.SubmissionDateValidator is a validator for the "submission_date" field. It is called by the builders before save.
	fnetdocument.SubmissionDateValidator = fnetdocumentDescSubmissionDate.Validators[0].(func(string) error)
	// fnetdocumentDescSubmissionMethodDescription is the schema descriptor for submission_method_description field.
	fnetdocumentDescSubmissionMethodDescription := fnetdocumentFields[15].Descriptor()
	// fnetdocument.SubmissionMethodDescriptionValidator is a validator for the "submission_method_description" field. It is called by the builders before save.
	fnetdocument.SubmissionMethodDescriptionValidator = fnetdocumentDescSubmissionMethodDescription.Validators[0].(func(string) error)
	// fnetdocumentDescSubmissionMethod is the schema descriptor for submission_method field.
	fnetdocumentDescSubmissionMethod := fnetdocumentFields[16].Descriptor()
	// fnetdocument.SubmissionMethodValidator is a validator for the "submission_method" field. It is called by the builders before save.
	fnetdocument.SubmissionMethodValidator = fnetdocumentDescSubmissionMethod.Validators[0].(func(string) error)
	// fnetdocumentDescVersion is the schema descriptor for version field.
	fnetdocumentDescVersion := fnetdocumentFields[17].Descriptor()
	// fnetdocument.VersionValidator is a validator for the "version" field. It is called by the builders before save.
	fnetdocument.VersionValidator = fnetdocumentDescVersion.Validators[0].(func(int) error)
}
